### ISSUE TITLE
Camera Filter using Bitmap

### ISSUE THREAD

**Issue by chiennc8** [PearKMA/CameraFilter#1]
I want to use a filter for the camera with a bitmap. In your code, where is the bitmap, which means texture2, initialized?

**Comment by hunglvv** [comment]
> I want to use a filter for the camera with a bitmap. In your code, where is the bitmap, which means texture2, initialized?

This is a custom filter for [this](https://github.com/natario1/CameraView). All you need to do is pass the bitmap you want to blend into this filter. Something like: 
`cameraView.setFilter(CameraFilterBlend(yourBlendBitmap));`

**Comment by PearKMA** [comment]
> I want to use a filter for the camera with a bitmap. In your code, where is the bitmap, which means texture2, initialized?

This is a custom filter for [this](https://github.com/natario1/CameraView). All you need to do is pass the bitmap you want to blend into this filter. Something like: 
```
CameraFilterBlend blendFilter = new CameraFilterBlend();
blendFilter.setBlendTexture(your_blend_bitmap);
cameraView.setFilter(blendFilter);
```
